---
# use Git Projet https://github.com/GuillaumeWaignier/ansible-raspberry-elasticsearch.git
# to install Elasticsearch and kibana



- name: Install metric collector
  hosts: collector
  roles:
  - role: collector
    tags: collector
  vars:
    - cronMinute: "*/5"
    - fibaro_login: "stats"
    - fibaro_url: "http://192.168.2.13"

  vars_prompt:
    - name: fibaro_password
      prompt: fibaro password
    - name: neo4j_password
      prompt: Neo4j Password

...
