---

user: "fibaro"
group: "fibaro"
base_directory: "/elk"

fibaro_login: a
fibaro_password: b
fibaro_url: "http://localhost"

cronMinute: 5

elasticsearch_url: "http://localhost:9200"
elasticsearch_index: "hc3_fibaro_climate"
elasticsearch_index_power: "hc3_fibaro_power"
elasticsearch_roll_size: "100mb"
elasticsearch_roll_date: "90d"
elasticsearch_delete_date: "10951d"

neo4j_url: "http://localhost:7474"
neo4j_user: "neo4j"
neo4j_password: "m"
neo4j_db: "neo4j"

...